### ISSUE TITLE
Can't add dns servers as ServerObject

### ISSUE THREAD

**Issue by linsui** [SagerNet/SagerNet#161]
**Describe the bug**
A v2ray cistum config with dns ServerObject produces `it.valueX must not be null` error.

**To Reproduce**
1. Add a v2ray custom config with dns ServerObject.
2. Connect

**Logcat**
```
07-02 22:42:08.205 31262 31262 W BaseService$Interface$onStartCommand$2: java.lang.NullPointerException: it.valueX must not be null
07-02 22:42:08.205 31262 31262 W BaseService$Interface$onStartCommand$2: 	at io.nekohasekai.sagernet.fmt.ConfigBuilderKt.buildCustomConfig(Unknown Source:4)
07-02 22:42:08.205 31262 31262 W BaseService$Interface$onStartCommand$2: 	at io.nekohasekai.sagernet.bg.ProxyInstance.init(Unknown Source:512)
07-02 22:42:08.205 31262 31262 W BaseService$Interface$onStartCommand$2: 	at io.nekohasekai.sagernet.bg.BaseService$Interface$onStartCommand$2.invokeSuspend(Unknown Source:55)
07-02 22:42:08.205 31262 31262 W BaseService$Interface$onStartCommand$2: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:2)
07-02 22:42:08.205 31262 31262 W BaseService$Interface$onStartCommand$2: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:86)
07-02 22:42:08.205 31262 31262 W BaseService$Interface$onStartCommand$2: 	at android.os.Handler.handleCallback(Handler.java:938)
07-02 22:42:08.205 31262 31262 W BaseService$Interface$onStartCommand$2: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-02 22:42:08.205 31262 31262 W BaseService$Interface$onStartCommand$2: 	at android.os.Looper.loop(Looper.java:223)
07-02 22:42:08.205 31262 31262 W BaseService$Interface$onStartCommand$2: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
07-02 22:42:08.205 31262 31262 W BaseService$Interface$onStartCommand$2: 	at java.lang.reflect.Method.invoke(Native Method)
07-02 22:42:08.205 31262 31262 W BaseService$Interface$onStartCommand$2: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
07-02 22:42:08.205 31262 31262 W BaseService$Interface$onStartCommand$2: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
Export it yourself :)

**Expected behavior**
**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. MI6]
 - OS: Android 11
 - Version 0.2-rc1

**Additional context**

**Comment by nekohasekai** [comment]
Should be fixed

**Comment by linsui** [comment]
Yes, the latest version works. Thanks!
