### ISSUE TITLE
Bug: Crash when using arrow controler on TV

### ISSUE THREAD

**Issue by leohearts** [SagerNet/SagerNet#368]
**Before submitting an issue, please make sure you are using the latest version of SagerNet.**
Yes.

### Describe the bug

SagerNet crashes when using TV arrow remote controller

### To Reproduce

- Open SagerNet
- Press Left (Or down or sth) on TV remote controller
- Crash

### Debug Information

I got `permission denied` exporting log after it crashes. So it's the logcat:

```
02-13 10:43:00.081 11636 11636 E SagerNet: uncaughtException
02-13 10:43:00.081 11636 11636 E SagerNet: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
02-13 10:43:00.081 11636 11636 E SagerNet:      at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
02-13 10:43:00.081 11636 11636 E SagerNet:      at java.util.ArrayList.get(ArrayList.java:308)
02-13 10:43:00.081 11636 11636 E SagerNet:      at io.nekohasekai.sagernet.ui.ConfigurationFragment.getSelectedGroup(ConfigurationFragment.kt:3)
02-13 10:43:00.081 11636 11636 E SagerNet:      at io.nekohasekai.sagernet.ui.ConfigurationFragment.onKeyDown(ConfigurationFragment.kt:1)
02-13 10:43:00.081 11636 11636 E SagerNet:      at io.nekohasekai.sagernet.ui.MainActivity.onKeyDown(MainActivity.kt:18)
02-13 10:43:00.081 11636 11636 E SagerNet:      at android.view.KeyEvent.dispatch(KeyEvent.java:2663)
02-13 10:43:00.081 11636 11636 E SagerNet:      at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:19)
02-13 10:43:00.081 11636 11636 E SagerNet:      at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:3)
02-13 10:43:00.081 11636 11636 E SagerNet:      at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:4)
02-13 10:43:00.081 11636 11636 E SagerNet:      at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2)
02-13 10:43:00.081 11636 11636 E SagerNet:      at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2310)
02-13 10:43:00.081 11636 11636 E SagerNet:      at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4166)
02-13 10:43:00.081 11636 11636 E SagerNet:      at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4128)
02-13 10:43:00.081 11636 11636 E SagerNet:      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3673)
02-13 10:43:00.081 11636 11636 E SagerNet:      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3726)
02-13 10:43:00.081 11636 11636 E SagerNet:      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3692)
02-13 10:43:00.081 11636 11636 E SagerNet:      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3818)
02-13 10:43:00.081 11636 11636 E SagerNet:      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3700)
02-13 10:43:00.081 11636 11636 E SagerNet:      at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3875)
02-13 10:43:00.081 11636 11636 E SagerNet:      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3673)
02-13 10:43:00.081 11636 11636 E SagerNet:      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3726)
02-13 10:43:00.081 11636 11636 E SagerNet:      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3692)
02-13 10:43:00.081 11636 11636 E SagerNet:      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3700)
02-13 10:43:00.081 11636 11636 E SagerNet:      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3673)
02-13 10:43:00.081 11636 11636 E SagerNet:      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3726)
02-13 10:43:00.081 11636 11636 E SagerNet:      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3692)
02-13 10:43:00.081 11636 11636 E SagerNet:      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3851)
02-13 10:43:00.081 11636 11636 E SagerNet:      at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4020)
02-13 10:43:00.081 11636 11636 E SagerNet:      at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2253)
02-13 10:43:00.081 11636 11636 E SagerNet:      at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1874)
02-13 10:43:00.081 11636 11636 E SagerNet:      at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1865)
02-13 10:43:00.081 11636 11636 E SagerNet:      at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2230)
02-13 10:43:00.081 11636 11636 E SagerNet:      at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
02-13 10:43:00.081 11636 11636 E SagerNet:      at android.os.MessageQueue.nativePollOnce(Native Method)
02-13 10:43:00.081 11636 11636 E SagerNet:      at android.os.MessageQueue.next(MessageQueue.java:323)
02-13 10:43:00.081 11636 11636 E SagerNet:      at android.os.Looper.loop(Looper.java:141)
02-13 10:43:00.081 11636 11636 E SagerNet:      at android.app.ActivityThread.main(ActivityThread.java:5427)
02-13 10:43:00.081 11636 11636 E SagerNet:      at java.lang.reflect.Method.invoke(Native Method)
02-13 10:43:00.081 11636 11636 E SagerNet:      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
02-13 10:43:00.081 11636 11636 E SagerNet:      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
```

### Expected behavior

It works

### Screenshots

![image](https://user-images.githubusercontent.com/24632029/153736144-b3aeb780-2fcc-40ca-aa8d-e2844a2b1270.png)

### Smartphone (please complete the following information)

- Kernel version: 3.14.29
- Device: MiBox 4
- OS: Android 6.0.1

### Additional context

I remember It works well on an old version. This problem occurred after updated to the newest version. (I've already tried uninstall and reinstall)

**Comment by nekohasekai** [comment]
Thanks!
