### ISSUE TITLE
URL test点完后崩溃闪退回桌面

### ISSUE THREAD

**Issue by Jimmisama** [SagerNet/SagerNet#380]
### 描述问题

点击Url test后1s左右闪退回桌面

### 如何复现

点右上角三个点点连接测试然后点Url Test

### 调试信息
```
--------- beginning of main
W/v2ray-core: V2Ray 5.0.8 started
W/v2ray-core: app/dispatcher: default route for tcp:api.v2fly.org:443
E/Go      : panic: interface conversion: interface {} is nil, not dnsmessage.Type
E/Go      :
E/Go      : goroutine 74 [running]:
E/Go      : github.com/v2fly/v2ray-core/v5/app/dns.(*Client).writeBack(0x40001e2d20, 0x40001f2d80, 0x40001c4f50)
E/Go      :     github.com/v2fly/v2ray-core/v5@v5.0.3/app/dns/dns.go:750 +0x18b0
E/Go      : github.com/v2fly/v2ray-core/v5/app/dns.(*Client).writeBackRaw(0x4000155e40?, 0x40001f2d80, 0x40004232f0)
E/Go      :     github.com/v2fly/v2ray-core/v5@v5.0.3/app/dns/dns.go:705 +0x1f4
E/Go      : github.com/v2fly/v2ray-core/v5/app/dns.(*Client).lookup.func4()
E/Go      :     github.com/v2fly/v2ray-core/v5@v5.0.3/app/dns/dns.go:328 +0x1b4
E/Go      : created by github.com/v2fly/v2ray-core/v5/app/dns.(*Client).lookup
E/Go      :     github.com/v2fly/v2ray-core/v5@v5.0.3/app/dns/dns.go:321 +0x13d4
--------- beginning of crash
F/libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 7817 (asekai.sagernet), pid 7796 (asekai.sagernet)
E/DEBUG   : failed to read /proc/uptime: Permission denied
F/DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
F/DEBUG   : Build fingerprint: 'google/raven/raven:12/SQ1D.220205.004/8151327:user/release-keys'
F/DEBUG   : Revision: 'MP1.0'
F/DEBUG   : ABI: 'arm64'
F/DEBUG   : Timestamp: 2022-02-24 03:29:26.941494847+0800
F/DEBUG   : Process uptime: 0s
F/DEBUG   : Cmdline: io.nekohasekai.sagernet
F/DEBUG   : pid: 7796, tid: 7817, name: asekai.sagernet  >>> io.nekohasekai.sagernet <<<
F/DEBUG   : uid: 10310
F/DEBUG   : tagged_addr_ctrl: 0000000000000001
F/DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
F/DEBUG   :     x0  0000000000000000  x1  0000000000001e89  x2  0000000000000006  x3  0000000000000008
F/DEBUG   :     x4  0000000000000001  x5  0000000000000000  x6  000000790babc2a0  x7  000000000000000a
F/DEBUG   :     x8  0000000000000083  x9  000000790c589bc8  x10 0000000000000042  x11 000000790bfbdcc9
F/DEBUG   :     x12 0000000000000001  x13 0000000000000000  x14 0000000000000000  x15 0000000000000000
F/DEBUG   :     x16 00000078e0c46340  x17 00000078e0d3dac0  x18 00000078de65c000  x19 0000000000001e74
F/DEBUG   :     x20 00000078e0d3d690  x21 0000004000100000  x22 000000790b9620a0  x23 00000004a24a2fd1
F/DEBUG   :     x24 bf6747b9283720d1  x25 4ba3f48d55a6f0c0  x26 0000000000000000  x27 0000000000000010
F/DEBUG   :     x28 00000040000a9040  x29 000000400048d928
F/DEBUG   :     lr  000000790af4f734  sp  000000400048d930  pc  000000790af6a5d8  pst 0000000080001000
F/DEBUG   : backtrace:
F/DEBUG   :       #00 pc 000000000031d5d8  /data/app/~~-JlfkRzTy4XZnUTqu9qB6w==/io.nekohasekai.sagernet-zQgCFiloag0uPB2jmyzrHw==/lib/arm64/libgojni.so
E/asekai.sagerne: Not starting debugger since process cannot load the jdwp agent.
I/libcore : updated root ca certificate list
E/ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
E/ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
E/ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
E/ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
E/ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
E/ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
E/ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
E/ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
E/ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
E/ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
E/ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
E/ViewDragHelper: Ignoring pointerId=0 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.`

```

### 预期行为

1s左右后程序闪退回桌面

### 屏幕截图

如果适用, 请添加屏幕截图以帮助解释您的问题.

### 设备信息

- 内核版本:  5.10.43-android12-9-00007-g9771767708df-ab8009062
- 设备型号: Google Pixel 6 Pro
- 操作系统: Android 12

### 附加上下文

同设备另一个bug，无法连接，连接开关会反复横跳.

**Comment by jelly0925** [comment]
我安卓11，更新到0.7-rc09后节点也是反复重启

**Comment by Jimmisama** [comment]
rc10已修复

**Comment by Jimmisama** [comment]
RC-11, 节点较多的时候（100+）具体哪个界限不清楚，问题依然存在
