### ISSUE TITLE
Crashes when two trojan-go upstreams are used simultaneously

### ISSUE THREAD

**Issue by DaZui** [SagerNet/SagerNet#85]
**Describe the bug**
When setting up router to route traffic to two individual trojan-go upstream proxies, trojan-go plugin crushes.

**To Reproduce**
1. Add two upstream that use trojan-go
2. In 'Router', add a custom route (content does not matter) and point it to use one of the upstream.
3. back to 'config', select the other upstream as major proxy and start VPN.
4. See error: libtrojan-go exits too fast (exit code: 1)

**Logcat**

```
05-10 16:19:39.006  7667  7667 I GoLog   : Preparing Domain: 127.0.0.1:2090
05-10 16:19:39.006  7667  7667 I GoLog   : Prepare Result:
05-10 16:19:39.006  7667  7667 I GoLog   :  Domain: 127.0.0.1
05-10 16:19:39.006  7667  7667 I GoLog   :  Port: 2090
05-10 16:19:39.006  7667  7667 I GoLog   :  IPs: [127.0.0.1]
05-10 16:19:39.006  7667  7667 I GoLog   : loading v2ray config
05-10 16:19:39.007 15241 15241 W libtrojan-go.so: type=1400 audit(0.0:7677): avc: denied { read } for name="somaxconn" dev="proc" ino=13985865 scontext=u:r:untrusted_app:s0:c70,c258,c512,c768 tcontext=u:object_r:proc_net:s0 tclass=file permissive=0 app=io.nekohasekai.sagernet
05-10 16:19:39.013  7667 15249 V libtrojan-go: [INFO]  2021/05/10 08:19:39 trojan-go Custom Version initializing
05-10 16:19:39.013  7667 15249 V libtrojan-go: [WARN]  2021/05/10 08:19:39 tls sni is unspecified
05-10 16:19:39.017  7667 15252 V libtrojan-go: [INFO]  2021/05/10 08:19:39 trojan-go Custom Version initializing
05-10 16:19:39.015 15250 15250 W libtrojan-go.so: type=1400 audit(0.0:7678): avc: denied { read } for name="somaxconn" dev="proc" ino=13985865 scontext=u:r:untrusted_app:s0:c70,c258,c512,c768 tcontext=u:object_r:proc_net:s0 tclass=file permissive=0 app=io.nekohasekai.sagernet
05-10 16:19:39.020  7667 15252 V libtrojan-go: [FATAL] 2021/05/10 08:19:39 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 adapter failed to create tcp listener | listen tcp 127.0.0.1:2091: bind: address already in use
05-10 16:19:39.339  7667  7667 I GoLog   : new v2ray core
05-10 16:19:39.354  7667  7667 I GoLog   : start v2ray core
05-10 16:19:39.354  7667  7667 I ProxyInstance$SagerSupportClass: onEmitStatus Running
05-10 16:19:39.354  7667 23579 I GoLog   : [Warning] V2Ray 4.39.0 started
05-10 16:19:39.366  7667  7667 I GuardedProcessPool: start process: /data/app/~~pL4ad6zCTojjCJkhkHBGww==/io.nekohasekai.sagernet-EflaY-IDqqED4yWPOESYlA==/lib/arm64/libtun2socks.so --netif-ipaddr 172.19.0.2 --socks-server-addr 127.0.0.1:2080 --tunmtu 1500 --sock-path /data/user_de/0/io.nekohasekai.sagernet/no_backup/sock_path --loglevel warning --dnsgw 127.0.0.1:6450 --netif-ip6addr fdfe:dcba:9876::2 --enable-udprelay
05-10 16:19:39.368  7667  7667 W GuardedProcessPool$Guard: error occurred. stop guard: /data/app/~~6nWGY5FrbEcSelf09Icn_w==/io.nekohasekai.sagernet.plugin.trojan_go-8rsVmJoC-0m0PXokOaKYRg==/lib/arm64/libtrojan-go.so -config /data/user/0/io.nekohasekai.sagernet/no_backup/trojan_go_86610533.json
05-10 16:19:39.368  7667  7667 W BaseService$Interface$onStartCommand$2$1: java.io.IOException: libtrojan-go exits too fast (exit code: 1)
05-10 16:19:39.368  7667  7667 W BaseService$Interface$onStartCommand$2$1: 	at io.nekohasekai.sagernet.bg.GuardedProcessPool$Guard.looper(GuardedProcessPool.kt:20)
05-10 16:19:39.368  7667  7667 W BaseService$Interface$onStartCommand$2$1: 	at io.nekohasekai.sagernet.bg.GuardedProcessPool$Guard$looper$1.invokeSuspend(Unknown Source:12)
05-10 16:19:39.368  7667  7667 W BaseService$Interface$onStartCommand$2$1: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
05-10 16:19:39.368  7667  7667 W BaseService$Interface$onStartCommand$2$1: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
05-10 16:19:39.368  7667  7667 W BaseService$Interface$onStartCommand$2$1: 	at android.os.Handler.handleCallback(Handler.java:938)
05-10 16:19:39.368  7667  7667 W BaseService$Interface$onStartCommand$2$1: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-10 16:19:39.368  7667  7667 W BaseService$Interface$onStartCommand$2$1: 	at android.os.Looper.loop(Looper.java:233)
05-10 16:19:39.368  7667  7667 W BaseService$Interface$onStartCommand$2$1: 	at android.app.ActivityThread.main(ActivityThread.java:8010)
05-10 16:19:39.368  7667  7667 W BaseService$Interface$onStartCommand$2$1: 	at java.lang.reflect.Method.invoke(Native Method)
05-10 16:19:39.368  7667  7667 W BaseService$Interface$onStartCommand$2$1: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
05-10 16:19:39.368  7667  7667 W BaseService$Interface$onStartCommand$2$1: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
05-10 16:19:39.371  7667  7667 I ProxyInstance$SagerSupportClass: onEmitStatus Closed
```

**Expected behavior**
Things should work to have two or more trojan-go upstream working together

**Additional context**

According to the logcat, it seems that the listening port (of one upstream) has been occupied by the other upstream.
```
05-10 16:19:39.020  7667 15252 V libtrojan-go: [FATAL] 2021/05/10 08:19:39 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 adapter failed to create tcp listener | listen tcp 127.0.0.1:2091: bind: address already in use
```

**Comment by nekohasekai** [comment]
Can't reproduce, have you updated to the latest version?

**Comment by DaZui** [comment]
fully uninstalled, removed configs, and reinstalled 1.0r6 and it fixed. 
Thank you so much for your hard work.
